
var data = {
    brands: [
        {
            brand: "Hyundai",
            models: [
                "Grand i10 Magna",
                "Creta SX Plus",
                "Elite i20 Magna",
                "i10 Magna 1.2",
                "Creta 1.6 SX",
                "i20 Sportz 1.2",
                "Santro Sportz CNG",
                "Grand i10 Asta",
                "Xcent S 1.2",
                "Grand i10 Sportz",
                "Elite i20 Sportz",
                "Eon Magna [2011-2012]",
                "Venue S 1.0",
                "Xcent SX 1.2",
                "Grand i10 Sports",
                "Verna Fluidic 1.6",
                "Xcent SX CRDi",
                "Verna 1.6 VTVT",
                "Santro Sportz AMT",
                "Grand i10 Nios",
                "i10 1.1L iRDE",
                "Creta SX 1.6",
                "i10 1.2 L",
                "Elite i20 Asta",
                "Tucson GLS 4WD",
                "Creta E Plus",
                "i20 Asta (O)",
                "Creta 1.6 S",
                "Eon Era +",
                "Santro Sportz",
                "Verna SX (O)",
                "Creta S 1.5",
                "i20 Active 1.2",
                "Venue SX 1.0",
                "Elantra 1.6 SX",
                "Santro Sportz [2018-2020]",
                "Creta 1.6 E",
                "Grand i10 Era",
                "Creta SX (O)",
                "Verna 1.4 VTVT",
                "i20 Asta 1.2",
                "i20 Magna 1.2",
                "i10 Sportz 1.2",
                "Xcent S 1.1",
                "Tucson 2WD MT",
                "Verna SX Plus",
                "Santro Xing GL",
                "Santro Magna [2018-2020]",
                "Creta Facelift 1.4",
                "Elantra SX (O)",
                "i10 Asta 1.2",
                "Venue SX 1.4",
                "i10 Magna 1.1",
                "Aura SX 1.2",
                "i20 Sportz 1.4",
                "Eon 1.0 Kappa",
                "Eon Era [2011-2012]",
                "i20 Magna (O)",
                "i10 Sportz 1.1",
                "Venue SX Plus",
                "Elantra 1.8 SX",
                "Alcazar Prestige (O)",
                "i20 Sportz (AT)",
                "i20 Asta 1.0",
                "Venue S Plus",
                "Elite i20 Era",
                "Eon D-Lite +",
                "Venue SX (O)",
                "Eon D-Lite",
                "Creta 1.4 S",
                "Santa Fe 2WD",
                "Verna EX 1.6",
                "Santro Xing GLS",
                "Creta SX 1.5",
                "Venue SX 1.5",
                "i20 Sportz 1.5",
                "Verna SX 1.5",
                "Accent Executive",
                "Xcent SX 1.1",
                "Verna 1.6 CRDI",
                "i10 Magna",
                "Santro Xing XG"
            ],
        },
        {
            brand: "Maruti",
            models: [
                "Suzuki Alto 800",
                "Suzuki Ciaz ZXI+",
                "Suzuki Eeco 5",
                "Suzuki Ertiga VXi",
                "Suzuki Ciaz VDi+",
                "Suzuki Vitara Brezza",
                "Suzuki Ciaz Alpha",
                "Suzuki Baleno Alpha",
                "Suzuki Wagon R",
                "Suzuki Swift VDi",
                "Suzuki Swift ZDi",
                "Suzuki Swift DZire",
                "Suzuki S-Presso VXi",
                "Suzuki Baleno Delta",
                "Suzuki Baleno Sigma",
                "Suzuki Baleno Zeta",
                "Suzuki Ignis Zeta",
                "Suzuki Swift VXi",
                "Suzuki Swift ZXi",
                "Suzuki Ciaz Zeta",
                "Suzuki Ciaz Delta",
                "Suzuki Celerio VXi",
                "Suzuki Alto K10",
                "Suzuki Swift Dzire",
                "Suzuki Celerio ZXi",
                "Suzuki Ertiga VXI",
                "Suzuki Dzire ZXi",
                "Suzuki Ignis Delta",
                "Suzuki Estilo VXi",
                "Suzuki Dzire VXi",
                "Suzuki Ertiga Vxi",
                "Suzuki S-Cross Alpha",
                "Suzuki XL6 Zeta",
                "Suzuki Ignis Sigma",
                "Suzuki S-Cross Zeta",
                "Suzuki Dzire VDi",
                "Suzuki Baleno RS",
                "Suzuki Ciaz VXi",
                "Suzuki SX4 ZXi",
                "Suzuki Ritz VXI",
                "Suzuki Ertiga ZXi",
                "Suzuki Ignis Alpha",
                "Suzuki Ciaz Sigma",
                "Suzuki Swift LXi",
                "Suzuki Dzire ZDi",
                "Suzuki Celerio X",
                "Suzuki Ritz Vdi",
                "Suzuki Ciaz S",
                "Suzuki Ciaz ZXi",
                "Suzuki Ertiga VDi",
                "Suzuki S-Cross Delta",
                "Suzuki Ritz Vxi",
                "Suzuki A-Star Vxi",
                "Suzuki Alto LXi",
                "Suzuki Estilo LXi",
                "Suzuki XL6 Alpha",
                "Suzuki SX4 VXI",
                "Suzuki A-Star VXI",
                "Suzuki Ciaz VXi+",
            ],
        },
        {
            brand: "Tata",
            models: [
                "Safari XZ Plus",
                "Nexon XZ Plus",
                "Tiago Revotron XZA",
                "Tiago Revotron XT",
                "Indica LS",
                "Tiago JTP 1.2",
                "Nexon XMA Diesel",
                "Safari XTA Plus",
                "Harrier XZ Plus",
                "Hexa XTA 4x2",
                "Harrier XZ [2019-2020]",
                "Nano Twist XT",
                "Tiago Revotorq XZ",
                "Tiago XZ Plus",
                "Tiago Revotron XE",
                "Harrier XZA Plus",
                "Indica V2 DLE",
                "Nexon XZA Plus",
                "Nexon EV XZ",
                "Tigor Buzz Petrol",
                "Harrier XTA Plus",
                "Tiago Revotron XZ",
                "Nexon XMA Petrol",
                "Safari XZA Plus",
                "Zest XM 75",
                "Altroz XZ (O)",
                "Harrier XT Plus",
                "Altroz XZ Petrol",
                "Indigo eCS LS",
                "Tiago NRG Petrol",
                "Harrier XZ",
                "Nexon XZ",
                "Altroz XZ Plus",
                "Nexon EV Prime",
                "Altroz XT Petrol",
                "Safari Storme 2.2",
                "Tigor EV XZ",
                "Nexon XT [2017-2019]",
                "Tigor Revotron XZ",
                "Nexon XM",
                "Nexon XMA (S)",
                "Harrier Kaziranga XZA",
                "Tiago XE",
                "Safari XZA New",
            ],
        },
        {
            brand: "Jeep",
            models: [
                "Compass Sport Plus", 
                "Compass Longitude 2.0", 
                "Compass Limited 1.4", 
                "Compass Limited Plus",
                "Wrangler Rubicon",
                "Compass Limited (O)",
                "Compass Sport 1.4",
                "Compass Model S",
                "Compass Longitude (O)",
                "Compass Limited 2.0",
                "Grand Cherokee SRT",
            ],
        },
        {
            brand: "Toyota",
            models: [
                "Etios Liva G",
                "Corolla Altis VL",
                "Glanza G CVT",
                "Glanza V",
                "Glanza G",
                "Innova Crysta ZX",
                "Innova 2.5 G",
                "Fortuner 2.8 4x4",
                "Corolla Altis G",
                "Corolla Altis 1.8",
                "Fortuner 2.8 4x2",
                "Fortuner Legender 4X2",
                "Etios Cross 1.2",
                "Corolla Altis JS",
                "Camry Hybrid",
                "Fortuner 4x2 AT",
                "Innova Crysta 2.4",
                "Yaris J CVT",
                "Etios VX",
                "Urban Cruiser High",
                "Innova 2.5 GX",
                "Innova 2.5 G2",
                "Yaris G CVT",
                "Yaris V CVT",
                "Corolla Altis GL",
                "Corolla H2 1.8E",
                "Yaris G MT",
                "Etios GD",
                "Yaris J MT",
                "Urban Cruiser Premium",
                "Etios Liva GD",
                "Fortuner 3.0 MT",
                "Fortuner 4X4 AT",
                "Land Cruiser LC",
                "Etios G",
            ],
        },
        {
            brand: "Renault",
            models: [
                "Kwid 1.0 RXT",
                "Kwid 1.0 RXL",
                "Kwid RXT [2015-2019]",
                "Triber RXZ EASY-R",
                "Duster 85 PS",
                "Kiger RXT Turbo",
                "Kwid CLIMBER 1.0",
                "Kwid RXL [2015-2019]",
                "Kwid RXL",
                "Duster 110 PS",
                "Kwid Neotech RXL",
                "Duster RXZ 1.3",
                "Kwid RXT 1.0",
                "Duster RXS CVT",
                "Captur RXL Petrol",
                "Triber RXL [2019-2020]",
                "Triber RXZ [2019-2020]",
                "Duster RXL Petrol",
                "Captur RXT Petrol",
            ],
        },
        {
            brand: "Chevrolet",
            models: [
                "Optra Magnum LS", 
                "Cruze LTZ AT", 
                "Beat LS Diesel", 
                "Cruze LTZ", 
                "Tavera Neo 3"
            ],
        },
        {
            brand: "Mercedes-Benz",
            models: [
                "EQC 400 4MATIC", 
                "GLC 200 Progressive", 
                "E-Class E 200", 
                "C-Class 220 BlueEfficiency", 
                "C-Class 200 K", 
                "S-Class 350 CDI", 
                "E-Class E 220", 
                "E-Class E350 CDI", 
                "GLS 350 d", 
                "CLA 200 CDI", 
                "CLA 200 Petrol", 
                "GLE 350 d", 
                "AMG GLA35 4MATIC",
                "C-Class C 200",
                "GLA 220 d",
                "C-Class C 220",
                "A-Class A 200d",
                "GLC 220 d",
                "E-Class E250 CDI",
                "C-Class 250 CDI",
                "E-Class E 220d",
                "GLE 250 d",
                "CLA 200 D",
                "GLA 200 d",
                "S-Class 350 L",
                "E-Class 280",
                "R-Class R350 4MATIC",
                "C-Class C 220d",
                "E-Class E 350",
                "GLC 220d 4MATIC",
                "B-Class B180 CDI",
                "S-Class Maybach S",
                "GLA 200 CDI",
                "CLS 350",
                "AMG A35 4MATIC",
                "C-Class C 300d",
                "GLE 300d 4MATIC",
                "GLA 200 Sport",
                "GL 350 CDI",
                "S-Class S 350",
            
            ],
        },
        {
            brand: "Ford",
            models: [
                "EcoSport Titanium 1.5L",
                "Figo Duratec Petrol",
                "Endeavour Titanium 3.2",
                "EcoSport Ambiente 1.5L",
                "EcoSport Titanium 1.0",
                "EcoSport Titanium+ 1.5L",
                "Aspire Titanium 1.2",
                "EcoSport Titanium 1.5",
                "EcoSport Titanium +",
                "Figo Duratorq Diesel",
                "EcoSport Signature Edition",
                "Figo Titanium 1.5",
                "Fiesta Exi 1.6",
                "Freestyle Trend Plus",
                "Freestyle Titanium Plus",
                "Aspire Titanium Plus",
                "Endeavour Titanium Plus",
                "Fiesta Classic SXi",
                "Classic 1.4 TDCi",
                "Endeavour Titanium 2.2",
                "EcoSport Trend 1.5L",
                "EcoSport Trend 1.5",
                "Figo Trend 1.2",
                "Aspire Trend Plus",
                "Figo Titanium1.5 TDCi",
                
            ],
        },
        {
            brand: "Porsche",
            models: [
                "718 Boxster",
                "Cayenne Turbo",
            ],
        },
        {
            brand: "Kia",
            models: [
                "Seltos HTE 1.5",
                "Seltos HTK 1.5",
                "Seltos GTX 1.4",
                "Carnival Prestige 7",
                "Seltos GTX Plus",
                "Sonet GTX Plus",
                "Seltos HTX 1.5",
                "Seltos HTX IVT",
                "Sonet HTX 1.0",
                "Sonet HTE 1.2",
                "Seltos GTX (O)",
                "Sonet HTX 1.5",
                "Seltos HTX Plus",
                "Seltos GTK 1.4",
                "Seltos HTK Plus",
                "Sonet HTX Plus",
                "Sonet HTK Plus",
            ],
        },
    ],
};

window.onload = function () {
    const selectState = document.getElementById("brand");
    const selectDistrict = document.getElementById("model");
    selectDistrict.disabled = true;

    //Add State Value to State Select option
    data.brands.forEach((value) => {
        selectState.appendChild(createOption(value.brand, value.brand));
    });

    selectState.addEventListener("change", function (e) {
        selectDistrict.disabled = false;
        data.brands.forEach((detail, index) => {
            //console.log(data.brands[index].models);
            if (detail.brand == e.target.value) {
                selectDistrict.innerHTML = "";
                selectDistrict.append(createOption("Select Model", ""));
                data.brands[index].models.forEach((district) => {
                    selectDistrict.append(createOption(district, district));
                });
            }
        });
    });

    //Create New Option Tag With Value
    function createOption(displayMember, valueMember) {
        const newOption = document.createElement("option");
        newOption.value = valueMember;
        newOption.text = displayMember;
        return newOption;
    }
};